"""Git hook generator for sv0-mcp graph memory synchronization."""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)

HOOK_TEMPLATE = """\
#!/bin/bash
# sv0-mcp post-commit hook
# Auto-generated by sv0-mcp. Triggers graph memory sync after commits.

SCOPE="{scope}"
SV0_MCP_DIR="{sv0_mcp_dir}"

if command -v sv0-mcp &>/dev/null; then
    sv0-mcp sync --scope "$SCOPE" &
elif [ -d "$SV0_MCP_DIR" ]; then
    cd "$SV0_MCP_DIR" && uv run sv0-mcp sync --scope "$SCOPE" &
fi
"""

_MARKER_START = "# --- sv0-mcp start ---"
_MARKER_END = "# --- sv0-mcp end ---"

_REPO_SCOPES: dict[str, str] = {
    "sv0doc": "spec",
    "sv0c": "compiler",
    "sv0vm": "vm",
}


def generate_hook(scope: str, sv0_mcp_dir: Path) -> str:
    """Generate a standalone post-commit hook script for the given scope.

    Args:
        scope: The sync scope (e.g. ``"spec"``, ``"compiler"``, ``"vm"``).
        sv0_mcp_dir: Absolute path to the sv0-mcp project directory.

    Returns:
        The complete hook script as a string, including shebang.
    """
    return HOOK_TEMPLATE.format(scope=scope, sv0_mcp_dir=sv0_mcp_dir)


def _hook_section(scope: str, sv0_mcp_dir: Path) -> str:
    """Generate a marker-delimited hook section for embedding in existing hooks.

    Args:
        scope: The sync scope.
        sv0_mcp_dir: Absolute path to the sv0-mcp project directory.

    Returns:
        A marker-wrapped section suitable for appending to an existing hook.
    """
    return (
        f"{_MARKER_START}\n"
        f"# sv0-mcp post-commit hook (auto-generated)\n"
        f'SCOPE="{scope}"\n'
        f'SV0_MCP_DIR="{sv0_mcp_dir}"\n'
        "\n"
        "if command -v sv0-mcp &>/dev/null; then\n"
        '    sv0-mcp sync --scope "$SCOPE" &\n'
        'elif [ -d "$SV0_MCP_DIR" ]; then\n'
        '    cd "$SV0_MCP_DIR" && uv run sv0-mcp sync --scope "$SCOPE" &\n'
        "fi\n"
        f"{_MARKER_END}\n"
    )


def install_hooks(toolchain_root: Path, sv0_mcp_dir: Path) -> list[str]:
    """Install post-commit hooks in sv0doc/, sv0c/, sv0vm/ git repos.

    Only installs if the ``.git`` directory exists. Does **not** overwrite
    existing hooks — appends a marker-delimited section or creates a new file.

    Args:
        toolchain_root: Root directory of the sv0-toolchain.
        sv0_mcp_dir: Absolute path to the sv0-mcp project directory.

    Returns:
        List of installed hook file paths.
    """
    installed: list[str] = []

    for repo_dir, scope in _REPO_SCOPES.items():
        git_dir = toolchain_root / repo_dir / ".git"
        if not git_dir.is_dir():
            logger.debug("No .git directory in %s, skipping", repo_dir)
            continue

        hooks_dir = git_dir / "hooks"
        hooks_dir.mkdir(exist_ok=True)
        hook_path = hooks_dir / "post-commit"
        section = _hook_section(scope, sv0_mcp_dir)

        if hook_path.exists():
            content = hook_path.read_text()
            if _MARKER_START in content:
                logger.info("Hook already installed in %s, skipping", repo_dir)
                continue
            content = content.rstrip("\n") + "\n\n" + section
            hook_path.write_text(content)
            logger.info("Appended sv0-mcp hook to %s", hook_path)
        else:
            hook_path.write_text("#!/bin/bash\n\n" + section)
            logger.info("Created sv0-mcp hook at %s", hook_path)

        hook_path.chmod(0o755)
        installed.append(str(hook_path))

    return installed


def uninstall_hooks(toolchain_root: Path) -> list[str]:
    """Remove sv0-mcp post-commit hook sections from sv0doc/, sv0c/, sv0vm/.

    Removes only the marker-delimited sv0-mcp section. If the hook file
    becomes empty (or contains only a shebang), the file is deleted entirely.

    Args:
        toolchain_root: Root directory of the sv0-toolchain.

    Returns:
        List of modified or removed hook file paths.
    """
    removed: list[str] = []

    for repo_dir in _REPO_SCOPES:
        hook_path = toolchain_root / repo_dir / ".git" / "hooks" / "post-commit"
        if not hook_path.exists():
            continue

        content = hook_path.read_text()
        if _MARKER_START not in content:
            continue

        lines = content.splitlines(keepends=True)
        new_lines: list[str] = []
        in_section = False
        for line in lines:
            stripped = line.strip()
            if stripped == _MARKER_START:
                in_section = True
                continue
            if stripped == _MARKER_END:
                in_section = False
                continue
            if not in_section:
                new_lines.append(line)

        remaining = "".join(new_lines).strip()
        if not remaining or remaining == "#!/bin/bash":
            hook_path.unlink()
            logger.info("Removed hook file %s", hook_path)
        else:
            hook_path.write_text(remaining + "\n")
            logger.info("Removed sv0-mcp section from %s", hook_path)

        removed.append(str(hook_path))

    return removed
